### ISSUE TITLE
rlottie missing

### ISSUE THREAD

**Issue by jlslinux** [batden/emeritux#1]
Hi 
Your script is giving error on rlottie missing, so I had to install form 
https://github.com/Samsung/rlottie

**Comment by batden** [comment]
Hi,
Thanks for your report!
Please make sure you're using the latest verstion of the script.
The rlottie library is not a hard requirement.
The error was caused by an incorrect flag: '-Devas-loaders-disabler='
added to the build_optim, rebuild_optim and rebuild_wld functions.
This should be fixed unless you are running an old version.
